### ISSUE TITLE
generateWaveformImage: w/ Antialiasing Enabled Producing Transparent Image

### ISSUE THREAD

**Issue by dyelax** [rFlex/SCWaveformView#4]
When I call SCWaveformView generateWaveformImage:asset withColor:[UIColor purpleColor] andSize:CGSizeMake(640, 332) antialiasingEnabled:YES];, the entire image is output as about 75% transparent, whereas if I pass in NO for antialiasingEnabled, I miss out on the smoothing of the edges, but at least the center of the waveform is fully opaque.

**Comment by rFlex** [comment]
Featured removed now.
